#!/bin/sh
#
# ATI open-source driver power management script created by Potoc.
#
#
# A "default" érték az alapértelmezett teljesítmény-állapot profilon hajtja a videokártyát. Ez az alap viselkedés.
# Az "auto" érték a "mid" és a "high" értékben definiált szinten tartja a kártyát, attól függően, hogy akkuról, vagy hálózatról megy-e a gép.
# A "low" érték kényszeríti a GPU-t az alacsony fogyasztású profil használatára. Néhány laptopon hibát okozhat, ezért sem használja az "auto" mód.
# A "low" érték vissza tudja szorítani a fogyasztást és a ventillátor sebességét, de nem lesz akkora a videoteljesítmény.
# A "mid" érték az arany középutat választja, közepes fogyasztást és teljesítményt ígér. Ha a képernyő kikapcsol, átvált "low" üzemmódba.
# A "high" érték a legmagasabb órajelen pörgeti a kártyát, terheléstől függetlenül. Nagy hangja lesz a videokártyának, nagy lesz a fogyasztás, cserébe a # legnagyobb teljesítményt nyújtja. Átvált "low" üzemmódba a képernyő kikapcsolásakor.
#
# A "dynpm" érték dinamikusan változtatja a kártya órajelét, tehát nagy órajelen fog menni a kártya a nagy GPU teljesítményt igénylő alkalmazások
# futásakor, kis órajelen amikor nincs terhelve. Ha ez van használatban, akkor zavaróan villoghat a kijelző a GPU órajel változtásakor, szóval más
# profilt kell használni ha ilyen jellegű probléma adódik. Főleg Compiz Fusion-t futtató embereknek szól!
#
# "default" uses the default clocks and does not change the power state. This is the default behavior.
# "auto" selects between "mid" and "high" power states based on the whether the system is on battery power or not. The "low" power state are selected
#  when # the monitors are in the dpms off state.
# "low" forces the gpu to be in the low power state all the time. Note that "low" can cause display problems on some laptops; this is why auto
#  does not use "low" when displays are active. (Can reduce power consumption and fan speed.)
# "mid" forces the gpu to be in the "mid" power state all the time. The "low" power state is selected when the monitors are in the dpms off state.
# "high" forces the gpu to be in the "high" power state all the time. The "low" power state is selected when the monitors are in the dpms off state.
# (When the high value is in use, the fan will be noisy, there is more power consumption, but we have better performance)
# 
#
# The "dynpm" method dynamically changes the clocks based on the number of pending fences, so performance is ramped up when running GPU intensive apps,  
# and ramped down when the GPU is idle. The reclocking is attemped during vertical blanking periods, but due to the timing of the reclocking functions, 
# doesn't not always complete in the blanking period, which can lead to flicker in the display. Due to this, dynpm only works when a single head is 
# active. 
# Dynpm can cause display flickering especially on Compiz Fusion! Use the others instead if you experience problems!
#
# >>>>>>>Copied from X.org Wiki<<<<<<<<

[ -n "$1" ] || { 
echo "Usage:
Run it as root!
  
sudo ./atiscript.sh [parameter]
  
  Usable parameters:

    --low     : low power consumption
    --mid     : mid power consumption
    --high    : high performance
    --default : runs card at default power state
    --auto    : vary between mid and high 
    --dynamic : frequency depends on load
    --help    : display full help
      ";
return ;}


case "$1" in
--low)

echo profile > /sys/class/drm/card0/device/power_method
echo low > /sys/class/drm/card0/device/power_profile

  ;;

--mid)

echo profile > /sys/class/drm/card0/device/power_method
echo mid > /sys/class/drm/card0/device/power_profile

  ;;

--high)

echo profile > /sys/class/drm/card0/device/power_method
echo high > /sys/class/drm/card0/device/power_profile

  ;;

--default)

echo profile > /sys/class/drm/card0/device/power_method
echo default > /sys/class/drm/card0/device/power_profile

;;

--auto)

echo profile > /sys/class/drm/card0/device/power_method
echo auto > /sys/class/drm/card0/device/power_profile

;;

--dynamic)

echo dynpm > /sys/class/drm/card0/device/power_method

;;

--help)
echo ' '
echo '"default" uses the default clocks and does not change the power state. This is the default behavior.'
echo '"auto" selects between "mid" and "high" power states based on the whether the system is on battery power or not.' 
echo 'The "low" power state are selected when echo ''the monitors are in the dpms off state.'
echo '"low" forces the gpu to be in the low power state all the time. Note that "low" can cause display problems on some laptops; this is why auto'
echo 'does not use "low" when displays are active. (Can reduce power consumption and fan speed.)'
echo '"mid" forces the gpu to be in the "mid" power state all the time. The "low" power state is selected when the monitors are in the dpms off state.'
echo 'high" forces the gpu to be in the "high" power state all the time. The "low" power state is selected when the monitors are in the dpms off state.'
echo '(When the high value is in use, the fan will be noisy, there is more power consumption, but we have better performance)' 
echo ' '
echo ' '
echo 'The "dynpm" method dynamically changes the clocks based on the number of pending fences,' 
echo 'so performance is ramped up when running GPU intensive apps,'
echo 'and ramped down when the GPU is idle. The reclocking is attemped during vertical blanking' 
echo 'periods, but due to the timing of the reclocking functions,' 
echo 'doesnt not always complete in the blanking period, which can lead to flicker in the display.'
echo 'Due to this, dynpm only works when a single head is active.' 
echo 'Dynpm can cause display flickering especially on Compiz Fusion! Use the others instead if'
echo 'you experience problems!'
echo ' '
echo ' '
echo '>>>>>>>Copied from X.org Wiki<<<<<<<<'

esac

exit 0
