[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 10.0

[font.normal]
family = "monospace"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
bindings = [
    { key = "Q", mode = "Vi|~Search", action = "ClearSelection" },
    { key = "Q", mode = "Vi|~Search", action = "ToggleViMode" },
    { key = "PageUp", mode = "Vi|~Search", action = "ScrollPageUp" },
    { key = "PageDown", mode = "Vi|~Search", action = "ScrollPageDown" },

    # Custom
    { key = "H", mods = "Control|Alt", action = "ClearHistory" },
    { key = "K", mods = "Control|Alt", command = { program = "sh", args = [
        "-c",
        "~/.local/bin/reset-active-tty",
    ] } },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "Enter", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "Up", mods = "Shift|Alt", action = "ScrollLineUp", mode = "~Alt" },
    { key = "Down", mods = "Shift|Alt", action = "ScrollLineDown", mode = "~Alt" },
    { key = "Back", mods = "Control", chars = "\u0017" },
]

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true

[window.padding]
x = 10
y = 5
